### ISSUE TITLE
Errors while Building

### ISSUE THREAD

**Issue by andrew95j** [airbus/ED247_LIBRARY#8]
I came across multiple CMake related errors when I was building the latest version of the library for MSVC 2017,  using the mgr.sh script.
 
- The first problem that I've encountered was CMake not being able to find the LibXML2 static libraries properly.
   I modified the "src/ed247/CMakeLists.txt" file by adding a SET command that sets the LibXML2_LIBRARY_DIR 
   path to the correct directory.
 
- While building tests, I've encountered quite a few "undefined reference" errors for GTest, Gmock.
   By adding absolute path variables to the GTest TARGET_LINK_LIBRARIES command in all  "/tests/.../CMakeLists.txt" files, my 
   issue was solved. 

- Still in the tests section, an "undefined reference" error also occured with Libiconv. Linking the iconv library with a  
  TARGET_LINK_LIBRARIES command in "/tests/test_lib/CMakeLists.txt" solves the error.
 
Manually changing CMake files proves to be quite difficult, and hopefully these issues can be solved for future releases.
 
I would also suggest adding an option for building the library with or without tests.

**Comment by gdelhomme** [comment]
Hello @andrew95j,

Thank you for your feedback. At the moment I am redesigning the development environment in order to get rid of the mgr.sh script and setup a more standard CMake compilation process. In addition, I will link required dependency repositories (libxml2 & gtest for test only) in order to allow their compilation in the same time.

Geoffrey

**Comment by gdelhomme** [comment]
New development environment available.
